name: Publich on crates.io

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install toml-cli
      run: cargo install toml-cli
    
    - name: Check version
      run: test "v$(toml get -r Cargo.toml package.version)" = "${{ github.ref_name }}"
      
    - name: Install bevy dependencies
      run: sudo apt-get install g++ pkg-config libx11-dev libasound2-dev libudev-dev libxkbcommon-x11-0
    
    - name: Publish
      run: cargo publish
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
